


CREATE TABLE "COARTIST_BUBBLE" (
	"CBID"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"ARTIST_NAME"	TEXT NOT NULL,
	"COARTIST_CATEGORY"	TEXT NOT NULL,
	"COARTIST_NAME"	TEXT NOT NULL,
	"BUBBLE_SCORE"	INTEGER NOT NULL
);


CREATE TABLE "ARTIST_SCORE" (
	"ASID"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"ARTIST_NAME"	TEXT NOT NULL,
	"YEAR"	INTEGER NOT NULL,
	"CRITIC_SCORE"	INTEGER NOT NULL,
	"AUDIENCE_SCORE"	INTEGER NOT NULL,
	"BOX_OFFICE_SCORE"	INTEGER NOT NULL
);