


CREATE TABLE "COARTIST_BUBBLE" (
	"CBID"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"ARTIST_NAME"	TEXT NOT NULL,
	"COARTIST_CATEGORY"	TEXT NOT NULL,
	"COARTIST_NAME"	TEXT NOT NULL,
	"BUBBLE_SCORE"	INTEGER NOT NULL
);