

INSERT INTO MOVIE (MOVIE_NAME, RELEASE_DATE) VALUES ('Asuran', '01 Oct 2019');

SELECT * FROM MOVIE;

INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Dhanush', '01 01 1983', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('TeeJay', '01 01 2003', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Yuvan Shankar Raja', '01 01 2003', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Nayanthara', '01 01 2003', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Vijay', '01 01 1983', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Shreya', '01 01 1986', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Vivek', '01 01 1973', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Thamanna', '01 01 1987', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Amala Paul', '01 01 1988', 'Chennai', 'India');

INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Ajith', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Simbu', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Surya', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Arya', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Prashanth', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Sarath Kumar', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Narain', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Vishal', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Arjun', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Sasi Kumar', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Vijay Sethupathi', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Rajini', '01 01 1993', 'Chennai', 'India');

INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Vikram', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Siddharth', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Rajini kanth', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Rajinikanth', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Kamal', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Jiiva', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Prasanna', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Madhavan', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Naga', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Cheran', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Maadavan', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('RaviKrishna', '01 01 1993', 'Chennai', 'India');

INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Atharvaa', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('PrabhuDeva', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Abhishek Bachchan', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('GauthamKarthik', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Sri', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Karthik', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('ShahRukhKhan', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('VijaySethupathi', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Vaibhav', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Karthi', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Udhayanidhini Stalin', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('GVPrakash', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('DulquerSalmaan', '01 01 1993', 'Chennai', 'India');
INSERT INTO PUBLIC_ARTIST (ARTIST_NAME, DOB, LOCATION, COUNTRY) VALUES ('Bharath', '01 01 1993', 'Chennai', 'India');


UPDATE PUBLIC_ARTIST 
SET DESCRIPTION = ""
WHERE WHERE ARTIST_NAME = 'Dhanush';

SELECT * FROM PUBLIC_ARTIST;


INSERT INTO MOVIE_ARTIST (MOVIE_ID, ARTIST_ID, ARTIST_ROLE) VALUES (1, 1, 'starring');
INSERT INTO MOVIE_ARTIST (MOVIE_ID, ARTIST_ID, ARTIST_ROLE) VALUES (1, 2, 'starring');

-- SHOW MOVIE ARTISTS
SELECT
	M.MID, 
	M.MOVIE_NAME, 
	M.RELEASE_DATE,
	MA.ARTIST_ID,
	PA.ARTIST_NAME
FROM MOVIE M
INNER JOIN MOVIE_ARTIST MA ON MA.MOVIE_ID = M.MID
INNER JOIN PUBLIC_ARTIST PA ON PA.AID = MA.ARTIST_ID;


INSERT INTO COARTIST_BUBBLE (ARTIST_ID, COARTIST_ID, COARTIST_CATEGORY, BUBBLE_SCORE) VALUES (1, 3, 'Music Director', 90); 
INSERT INTO COARTIST_BUBBLE (ARTIST_ID, COARTIST_ID, COARTIST_CATEGORY, BUBBLE_SCORE) VALUES (1, 4, 'Actress', 80); 

INSERT INTO COARTIST_BUBBLE (ARTIST_ID, COARTIST_ID, COARTIST_CATEGORY, BUBBLE_SCORE) VALUES (1, 6, 'Actress', 70); 
INSERT INTO COARTIST_BUBBLE (ARTIST_ID, COARTIST_ID, COARTIST_CATEGORY, BUBBLE_SCORE) VALUES (1, 7, 'Comedian', 67); 
INSERT INTO COARTIST_BUBBLE (ARTIST_ID, COARTIST_ID, COARTIST_CATEGORY, BUBBLE_SCORE) VALUES (1, 8, 'Actress', 82); 
INSERT INTO COARTIST_BUBBLE (ARTIST_ID, COARTIST_ID, COARTIST_CATEGORY, BUBBLE_SCORE) VALUES (1, 9, 'Actress', 89); 


INSERT INTO ARTIST_SCORE (ARTIST_ID, YEAR, CRITIC_SCORE, AUDIENCE_SCORE, BOX_OFFICE_SCORE) VALUES (1, 2011, 90, 80, 59);
INSERT INTO ARTIST_SCORE (ARTIST_ID, YEAR, CRITIC_SCORE, AUDIENCE_SCORE, BOX_OFFICE_SCORE) VALUES (1, 2012, 70, 56, 69);
INSERT INTO ARTIST_SCORE (ARTIST_ID, YEAR, CRITIC_SCORE, AUDIENCE_SCORE, BOX_OFFICE_SCORE) VALUES (1, 2013, 56, 89, 89);
INSERT INTO ARTIST_SCORE (ARTIST_ID, YEAR, CRITIC_SCORE, AUDIENCE_SCORE, BOX_OFFICE_SCORE) VALUES (1, 2014, 89, 56, 29);
INSERT INTO ARTIST_SCORE (ARTIST_ID, YEAR, CRITIC_SCORE, AUDIENCE_SCORE, BOX_OFFICE_SCORE) VALUES (1, 2015, 56, 78, 59);
INSERT INTO ARTIST_SCORE (ARTIST_ID, YEAR, CRITIC_SCORE, AUDIENCE_SCORE, BOX_OFFICE_SCORE) VALUES (1, 2016, 67, 45, 99);


INSERT INTO ARTIST_SCORE (ARTIST_ID, YEAR, CRITIC_SCORE, AUDIENCE_SCORE, BOX_OFFICE_SCORE) VALUES (5, 2011, 90, 80, 59);
INSERT INTO ARTIST_SCORE (ARTIST_ID, YEAR, CRITIC_SCORE, AUDIENCE_SCORE, BOX_OFFICE_SCORE) VALUES (5, 2012, 70, 56, 69);
INSERT INTO ARTIST_SCORE (ARTIST_ID, YEAR, CRITIC_SCORE, AUDIENCE_SCORE, BOX_OFFICE_SCORE) VALUES (5, 2013, 56, 89, 89);
INSERT INTO ARTIST_SCORE (ARTIST_ID, YEAR, CRITIC_SCORE, AUDIENCE_SCORE, BOX_OFFICE_SCORE) VALUES (5, 2014, 89, 56, 29);
INSERT INTO ARTIST_SCORE (ARTIST_ID, YEAR, CRITIC_SCORE, AUDIENCE_SCORE, BOX_OFFICE_SCORE) VALUES (5, 2015, 56, 78, 59);
INSERT INTO ARTIST_SCORE (ARTIST_ID, YEAR, CRITIC_SCORE, AUDIENCE_SCORE, BOX_OFFICE_SCORE) VALUES (5, 2016, 67, 45, 99);


SELECT 
	PA.AID AS  'ARTIST_ID', 
	PA.ARTIST_NAME AS 'ARTIST_NAME',
	COPA.AID AS 'COARTIST_ID',
	COPA.ARTIST_NAME AS 'COARTIST_NAME',
	COB.BUBBLE_SCORE AS 'BUBBLE_SCORE'
FROM COARTIST_BUBBLE COB
INNER JOIN PUBLIC_ARTIST PA ON COB.ARTIST_ID = PA.AID
INNER JOIN PUBLIC_ARTIST COPA ON COB.COARTIST_ID = COPA.AID
WHERE PA.ARTIST_NAME = 'Dhanush';


SELECT
	PA.AID AS 'ARTIST_ID',
	PA.ARTIST_NAME AS 'ARTIST_NAME',
	ASCORE.YEAR  AS 'ARTIST_YEAR',
	ASCORE.CRITIC_SCORE AS 'CRITIC_SCORE',
	ASCORE.AUDIENCE_SCORE AS 'AUDIENCE_SCORE',
	ASCORE.BOX_OFFICE_SCORE AS 'BOX_OFFICE_SCORE'
FROM ARTIST_SCORE ASCORE
INNER JOIN PUBLIC_ARTIST PA ON PA.AID = ASCORE.ARTIST_ID
WHERE PA.ARTIST_NAME = 'Dhanush' COLLATE NOCASE;