
DELETE FROM MOVIE;

DROP TABLE MOVIE;

CREATE TABLE "MOVIE" (
	"MID"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"MOVIE_NAME"	TEXT NOT NULL UNIQUE,
	"RELEASE_DATE"	TEXT
);





DELETE FROM PUBLIC_ARTIST;

DROP TABLE PUBLIC_ARTIST;

CREATE TABLE "PUBLIC_ARTIST" (
	"AID"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"ARTIST_NAME"	TEXT NOT NULL UNIQUE,
	"ORIGINAL_NAME" TEXT,
	"DOB"	TEXT,
	"LOCATION"	TEXT,
	"COUNTRY" TEXT
);


DELETE FROM MOVIE_ARTIST;

DROP TABLE MOVIE_ARTIST;

CREATE TABLE "MOVIE_ARTIST" (
	"MAID"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"MOVIE_ID"	TEXT NOT NULL,
	"ARTIST_ID"	INTEGER NOT NULL,
	"ARTIST_ROLE"	TEXT NOT NULL
);



DELETE FROM COARTIST_BUBBLE;

DROP TABLE COARTIST_BUBBLE;

CREATE TABLE "COARTIST_BUBBLE" (
	"CBID"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"ARTIST_ID"	TEXT NOT NULL,
	"COARTIST_CATEGORY"	TEXT NOT NULL,
	"COARTIST_ID"	TEXT NOT NULL,
	"BUBBLE_SCORE"	INTEGER NOT NULL
);



SELECT 
	PA.AID AS  'ARTIST_ID', 
	PA.ARTIST_NAME AS 'ARTIST_NAME',
	COPA.AID AS 'COARTIST_ID',
	COPA.ARTIST_NAME AS 'COARTIST_NAME',
	COB.BUBBLE_SCORE AS 'BUBBLE_SCORE'
FROM COARTIST_BUBBLE COB
INNER JOIN PUBLIC_ARTIST PA ON COB.ARTIST_ID = PA.AID
INNER JOIN PUBLIC_ARTIST COPA ON COB.COARTIST_ID = COPA.AID
WHERE PA.ARTIST_NAME = 'Dhanush';


DELETE FROM ARTIST_SCORE;

DROP TABLE ARTIST_SCORE;

CREATE TABLE "ARTIST_SCORE" (
	"ASID"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"ARTIST_ID"	TEXT NOT NULL,
	"YEAR"	INTEGER NOT NULL,
	"CRITIC_SCORE"	INTEGER NOT NULL,
	"AUDIENCE_SCORE"	INTEGER NOT NULL,
	"BOX_OFFICE_SCORE"	INTEGER NOT NULL
);


SELECT
	PA.AID AS 'ARTIST_ID',
	PA.ARTIST_NAME AS 'ARTIST_NAME',
	ASCORE.YEAR  AS 'ARTIST_YEAR',
	ASCORE.CRITIC_SCORE AS 'CRITIC_SCORE',
	ASCORE.AUDIENCE_SCORE AS 'AUDIENCE_SCORE',
	ASCORE.BOX_OFFICE_SCORE AS 'BOX_OFFICE_SCORE'
FROM ARTIST_SCORE ASCORE
INNER JOIN PUBLIC_ARTIST PA ON PA.AID = ASCORE.ARTIST_ID;