

SELECT * FROM MOVIE;
SELECT MID, MOVIE_NAME, RELEASE_DATE FROM MOVIE;



SELECT * FROM PUBLIC_ARTIST;



SELECT AID FROM PUBLIC_ARTIST WHERE ARTIST_NAME = 'Krishna';

-- SHOW MAARI 2 ARTISTS
SELECT
	MA.MOVIE_ID AS 'MOVIE_ID',
	M.MOVIE_NAME AS  'MOVIE_NAME',
	MA.ARTIST_ID AS 'ARTIST_ID',
	PA.ARTIST_NAME AS 'ARTIST_NAME',
	MA.ARTIST_ROLE AS 'ARTIST_ROLE'
FROM MOVIE_ARTIST MA
INNER JOIN MOVIE M ON M.MID = MA.MOVIE_ID
INNER JOIN PUBLIC_ARTIST PA ON PA.AID = MA.ARTIST_ID
WHERE M.MOVIE_NAME = 'Asuran' COLLATE NOCASE;

SELECT
	M.MID AS 'MOVIE_ID',
	M.MOVIE_NAME AS  'MOVIE_NAME',
	M.RELEASE_DATE AS 'RELEASE_DATE'
FROM MOVIE M
INNER JOIN MOVIE_ARTIST MA ON M.MID = MA.MOVIE_ID
INNER JOIN PUBLIC_ARTIST PA ON PA.AID = MA.ARTIST_ID
WHERE PA.ARTIST_NAME = 'Dhanush' COLLATE NOCASE;


-- SHOW MOVIE ARTISTS
SELECT
	M.MID, 
	M.MOVIE_NAME, 
	M.RELEASE_DATE,
	MA.ARTIST_ID,
	PA.ARTIST_NAME,
	MA.ARTIST_ROLE
FROM MOVIE M
INNER JOIN MOVIE_ARTIST MA ON MA.MOVIE_ID = M.MID
INNER JOIN PUBLIC_ARTIST PA ON PA.AID = MA.ARTIST_ID;


SELECT 
	PA.AID AS  'ARTIST_ID', 
	PA.ARTIST_NAME AS 'ARTIST_NAME',
	COPA.AID AS 'COARTIST_ID',
	COPA.ARTIST_NAME AS 'COARTIST_NAME',
	COB.BUBBLE_SCORE AS 'BUBBLE_SCORE'
FROM COARTIST_BUBBLE COB
INNER JOIN PUBLIC_ARTIST PA ON COB.ARTIST_ID = PA.AID
INNER JOIN PUBLIC_ARTIST COPA ON COB.COARTIST_ID = COPA.AID
WHERE PA.ARTIST_NAME = 'Dhanush' COLLATE NOCASE;


SELECT
	PA.AID AS 'ARTIST_ID',
	PA.ARTIST_NAME AS 'ARTIST_NAME',
	ASCORE.YEAR  AS 'ARTIST_YEAR',
	ASCORE.CRITIC_SCORE AS 'CRITIC_SCORE',
	ASCORE.AUDIENCE_SCORE AS 'AUDIENCE_SCORE',
	ASCORE.BOX_OFFICE_SCORE AS 'BOX_OFFICE_SCORE'
FROM ARTIST_SCORE ASCORE
INNER JOIN PUBLIC_ARTIST PA ON PA.AID = ASCORE.ARTIST_ID
WHERE PA.ARTIST_NAME = 'Dhanush' COLLATE NOCASE;


SELECT
	PA.AID AS 'ARTIST_ID'
FROM PUBLIC_ARTIST PA
WHERE PA.ARTIST_NAME = 'dhanush' COLLATE NOCASE;

-- GET ARTIST SCORE
SELECT
	PA.AID AS 'ARTIST_ID',
	PA.ARTIST_NAME AS 'ARTIST_NAME',
	ROUND(AVG(ASCO.CRITIC_SCORE), 2) AS 'CRITIC_SCORE',
	ROUND(AVG(ASCO.AUDIENCE_SCORE), 2) AS 'AUDIENCE_SCORE',
	ROUND(AVG(ASCO.CRITIC_SCORE), 2) AS 'BOX_OFFICE_SCORE'
FROM ARTIST_SCORE ASCO
INNER JOIN PUBLIC_ARTIST PA ON PA.AID = ASCO.ARTIST_ID;

-- GET
SELECT
	M.MID AS 'MOVIE_ID',
	M.MOVIE_NAME AS 'MOVIE_NAME',
	PA.AID AS 'ARTIST_ID',
	PA.ARTIST_NAME AS 'ARTIST_NAME',
	MA.ARTIST_ROLE AS 'ARTIST_ROLE'
FROM MOVIE M
INNER JOIN MOVIE_ARTIST MA ON M.MID = MA.MOVIE_ID
INNER JOIN PUBLIC_ARTIST PA ON PA.AID = MA.ARTIST_ID
WHERE PA.ARTIST_NAME = 'dhanush' COLLATE NOCASE;




-- GET DHANUSH MOVIES
SELECT
	M.MID AS 'MOVIE_ID',
	M.MOVIE_NAME AS 'MOVIE_NAME'
FROM MOVIE M
INNER JOIN MOVIE_ARTIST MA ON M.MID = MA.MOVIE_ID 
INNER JOIN PUBLIC_ARTIST PA ON PA.AID = MA.ARTIST_ID
WHERE PA.ARTIST_NAME = 'dhanush' 
COLLATE NOCASE;

-- GET MOVIES
SELECT
	PA.AID AS 'ARTIST_ID',
	PA.ARTIST_NAME AS 'ARTIST_NAME'
FROM MOVIE M
INNER JOIN MOVIE_ARTIST MA ON M.MID = MA.MOVIE_ID 
INNER JOIN PUBLIC_ARTIST PA ON PA.AID = MA.ARTIST_ID
WHERE M.MID = 1;


-- SELECT COARTIST BUBBLE
SELECT
	ARTIST_ID,
	ARTIST_CATEGORY,
	COARTIST_ID,
	COARTIST_CATEGORY,
	COUNT(BUBBLE_SCORE) AS 'VOTE_COUNT',
	ROUND(AVG(BUBBLE_SCORE), 2) AS 'BUBBLE_SCORE'
FROM COARTIST_BUBBLE COB
INNER JOIN PUBLIC_ARTIST PA ON PA.AID = COB.ARTIST_ID
WHERE PA.ARTIST_NAME = 'dhanush' COLLATE NOCASE
GROUP BY COARTIST_ID


SELECT
	ARTIST_ID,
	PA.ARTIST_NAME AS 'ARTIST_NAME',
	ARTIST_CATEGORY,
	COARTIST_ID,
	CPA.ARTIST_NAME AS 'CO_ARTIST_NAME',
	COARTIST_CATEGORY,
	COUNT(BUBBLE_SCORE) AS 'VOTE_COUNT',
	ROUND(AVG(BUBBLE_SCORE), 2) AS 'BUBBLE_SCORE'
FROM COARTIST_BUBBLE COB
INNER JOIN PUBLIC_ARTIST PA ON PA.AID = COB.ARTIST_ID
INNER JOIN PUBLIC_ARTIST CPA ON CPA.AID = COB.COARTIST_ID
WHERE PA.ARTIST_NAME = 'dhanush' COLLATE NOCASE
GROUP BY COARTIST_ID;


SELECT
	PA.AID AS 'ARTIST_ID',
	PA.ARTIST_NAME AS 'ARTIST_NAME',
	PA.LOCATION AS 'LOCAION', 
	PA.COUNTRY AS 'COUNTRY', 
	PA.DESCRIPTION AS 'DESCRIPTION', 
	PA.PIC_LOCATION AS 'PIC_LOCATION'
FROM PUBLIC_ARTIST PA
WHERE PA.ARTIST_NAME = 'dhanush' COLLATE NOCASE;